### ISSUE TITLE
Add Read receipts feature

### ISSUE THREAD

**Issue by harshshukla1609** [ContriHUB/Chamber_of_Secrets#1]
🚀Feature Request
I want to implement read receipts feature in this project.
Level - medium

Key Points -

1)Whenever a sender send a message to the receiver first the message reaches server you must get an acknowledgement that message has been sent to server.

2)When the message reaches from server to receiver you must get a delivered acknowledgement.

3)Whenever the receiver opens the application and your chat you must get an acknowledgement that the message is read by the receiver.

This feature will give you assurance whether your message is successfully delivered to the receiver or they have read your message.

**Comment by lakshitrajput** [comment]
I'd like to contribute
Can you assign me this issue

**Comment by nandani-01** [comment]
Can you assign this issue to me

**Comment by smt96700** [comment]
Dear @harshshukla1609, I have successfully set up your project locally and have experience with Socket.io; could you kindly assign the issue to me?

**Comment by nandani-01** [comment]
i m working on this issue.

**Comment by lakshitrajput** [comment]
@nandani-01 is ṭḥe issue assigned to you from the contri hub website ?
