### ISSUE TITLE
Add Last Seen Feature

### ISSUE THREAD

**Issue by harshshukla1609** [ContriHUB/Chamber_of_Secrets#3]
🚀Feature Request
I want to implement last seen feature in this project.
Level - medium

Key Points -
1) Server must store last seen for every user.
2) We must ensure only user activity based requests (if user tries to do something on the app) are counted for last seen.
     Any delivery receipt (acknowledgement for delivery message) should not be counted for last seen.
3) Display the last seen for every user on the UI.

**Comment by Vaishnavi1047** [comment]
@harshshukla1609 
![image](https://github.com/user-attachments/assets/5210f9ea-fd42-40e0-bc54-8046ab04c5b0)
force install ke baad bhi yeh dikkt kr rha

**Comment by harshshukla1609** [comment]
there might be some error in this repo till then anyone could use the local version of this project anyone can download it using this drive link. Very sorry for the inconvinence caused looking upon this problem
Link - "https://drive.google.com/file/d/1f5E2W12LcLbRkitZoVNcatB3RbO8QLxX/view?usp=sharing"
